
package ipd12.Java3.Project.StockTracker;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * @author Roman Shaiko, Dmitrii Kudrik
 */
public class MainWindow extends javax.swing.JFrame {
    
    Database db;
    
    public boolean isReal = true; //the app opens in TrackMode by default

    public MainWindow() {
        
        try {
            db = new Database();
            initComponents();

        } catch (SQLException ex) {
            ex.printStackTrace();
            // display dialog with error message and terminate the program
            JOptionPane.showMessageDialog(this,
                    "Fatal error: unable to connect to database:\n" + ex.getMessage(),
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgUser_lblPasswordOk = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dlgUser_tfUsername = new javax.swing.JTextField();
        dlgUser_tfPassword = new javax.swing.JPasswordField();
        dlgUser_btCancel = new javax.swing.JButton();
        dlgUser_btLogin = new javax.swing.JButton();
        dlgUser_lblHelpUserName = new javax.swing.JLabel();
        dlgUser_lblHelpPassword = new javax.swing.JLabel();
        dlgUser_lblUserOk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dlgUser_cbbDefaultUser = new javax.swing.JCheckBox();
        dlgUser_btSignUp = new javax.swing.JButton();
        dlgSignUp = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dlgSignUp_tfUsername = new javax.swing.JTextField();
        dlgSignUp_tfPassword = new javax.swing.JPasswordField();
        dlgSignUp_rbtCancel = new javax.swing.JButton();
        dlgSignUp_lblHelpUserName = new javax.swing.JLabel();
        dlgSignUp_lblHelpPassword = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dlgSignUp_lblPassOk = new javax.swing.JLabel();
        dlgSignUp_cbbDefaultUser = new javax.swing.JCheckBox();
        dlgSignUp_btSignUp = new javax.swing.JButton();
        dlgSignUp_tfPassConfirmation = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        dlgSignUp_lblUserOk = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dlgPortfolios = new javax.swing.JDialog();
        dlgMoving = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        dlgMoving_lblCurrentTrade = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dlgMoving_cbbChoosePortfolio = new javax.swing.JComboBox<>();
        dlgMoving_btMove = new javax.swing.JButton();
        dlgMoving_btCancel = new javax.swing.JButton();
        dlgManage = new javax.swing.JDialog();
        dlgManage_btnAdd = new javax.swing.JButton();
        dlgManage_btnEdit = new javax.swing.JButton();
        dlgManage_btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dlgManage_tfName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dlgManage_lblId = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dlgManage_cbbType = new javax.swing.JComboBox<>();
        dlgManage_tfCash = new javax.swing.JTextField();
        dlgManage_cbByDefault = new javax.swing.JCheckBox();
        ppMain = new javax.swing.JPopupMenu();
        ppMain_Move = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ppMain_Delete = new javax.swing.JMenuItem();
        dlgAdd = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTable = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btAddTrade = new javax.swing.JButton();
        btDeleteTrade = new javax.swing.JButton();
        btSaveChanges = new javax.swing.JButton();
        cbbPortfolio = new javax.swing.JComboBox<>();
        cbIsDefaultPortfolio = new javax.swing.JCheckBox();
        btMove = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        smExpExcel = new javax.swing.JMenuItem();
        smExpCsv = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        smExit = new javax.swing.JMenuItem();
        mTrade = new javax.swing.JMenu();
        mSwitch = new javax.swing.JMenu();
        mPortfolios = new javax.swing.JMenu();
        mReports = new javax.swing.JMenu();
        smReportCurrent = new javax.swing.JMenuItem();
        smReportAll = new javax.swing.JMenuItem();
        mEmpty = new javax.swing.JMenu();
        mUser = new javax.swing.JMenu();
        mLogin = new javax.swing.JMenu();

        dlgUser_lblPasswordOk.setResizable(false);
        dlgUser_lblPasswordOk.setSize(new java.awt.Dimension(380, 200));

        jLabel1.setText("Username");

        jLabel3.setText("Password");

        dlgUser_tfPassword.setText("jPasswordField1");

        dlgUser_btCancel.setText("Cancel");
        dlgUser_btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgUser_btCancelActionPerformed(evt);
            }
        });

        dlgUser_btLogin.setText("Log In");

        dlgUser_lblHelpUserName.setText("?");

        dlgUser_lblHelpPassword.setText("?");

        dlgUser_lblUserOk.setBackground(new java.awt.Color(0, 204, 0));
        dlgUser_lblUserOk.setForeground(new java.awt.Color(255, 51, 51));
        dlgUser_lblUserOk.setText("x");

        jLabel7.setBackground(new java.awt.Color(51, 204, 0));
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("");

        dlgUser_cbbDefaultUser.setText("Default user");

        dlgUser_btSignUp.setText("Sign Up");

        javax.swing.GroupLayout dlgUser_lblPasswordOkLayout = new javax.swing.GroupLayout(dlgUser_lblPasswordOk.getContentPane());
        dlgUser_lblPasswordOk.getContentPane().setLayout(dlgUser_lblPasswordOkLayout);
        dlgUser_lblPasswordOkLayout.setHorizontalGroup(
            dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgUser_lblPasswordOkLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                        .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dlgUser_lblHelpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dlgUser_tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(dlgUser_lblHelpPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dlgUser_tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                        .addComponent(dlgUser_btCancel)
                        .addGap(18, 18, 18)
                        .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlgUser_cbbDefaultUser)
                            .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                                .addComponent(dlgUser_btLogin)
                                .addGap(18, 18, 18)
                                .addComponent(dlgUser_btSignUp)))
                        .addGap(18, 18, 18)))
                .addComponent(dlgUser_lblUserOk, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );

        dlgUser_lblPasswordOkLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dlgUser_btCancel, dlgUser_btLogin, dlgUser_btSignUp});

        dlgUser_lblPasswordOkLayout.setVerticalGroup(
            dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgUser_lblPasswordOkLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dlgUser_tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgUser_lblHelpUserName)
                    .addComponent(dlgUser_lblUserOk)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dlgUser_tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgUser_lblHelpPassword))
                .addGap(18, 18, 18)
                .addComponent(dlgUser_cbbDefaultUser)
                .addGap(18, 18, 18)
                .addGroup(dlgUser_lblPasswordOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgUser_btCancel)
                    .addComponent(dlgUser_btLogin)
                    .addComponent(dlgUser_btSignUp))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        dlgSignUp.setResizable(false);
        dlgSignUp.setSize(new java.awt.Dimension(380, 200));

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        dlgSignUp_tfPassword.setText("jPasswordField1");

        dlgSignUp_rbtCancel.setText("Cancel");
        dlgSignUp_rbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgSignUp_rbtCancelActionPerformed(evt);
            }
        });

        dlgSignUp_lblHelpUserName.setText("?");

        dlgSignUp_lblHelpPassword.setText("?");

        jLabel8.setBackground(new java.awt.Color(0, 204, 0));
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("x");

        dlgSignUp_lblPassOk.setBackground(new java.awt.Color(51, 204, 0));
        dlgSignUp_lblPassOk.setForeground(new java.awt.Color(51, 204, 0));
        dlgSignUp_lblPassOk.setText("");

        dlgSignUp_cbbDefaultUser.setText("Default user");

        dlgSignUp_btSignUp.setText("Sign Up");

        dlgSignUp_tfPassConfirmation.setText("jPasswordField1");
        dlgSignUp_tfPassConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgSignUp_tfPassConfirmationActionPerformed(evt);
            }
        });

        jLabel10.setText("Confirm");

        dlgSignUp_lblUserOk.setBackground(new java.awt.Color(51, 204, 0));
        dlgSignUp_lblUserOk.setForeground(new java.awt.Color(51, 204, 0));
        dlgSignUp_lblUserOk.setText("");

        jLabel12.setBackground(new java.awt.Color(0, 204, 0));
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("x");

        javax.swing.GroupLayout dlgSignUpLayout = new javax.swing.GroupLayout(dlgSignUp.getContentPane());
        dlgSignUp.getContentPane().setLayout(dlgSignUpLayout);
        dlgSignUpLayout.setHorizontalGroup(
            dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgSignUpLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSignUpLayout.createSequentialGroup()
                        .addComponent(dlgSignUp_rbtCancel)
                        .addGap(49, 49, 49)
                        .addComponent(dlgSignUp_btSignUp)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dlgSignUpLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(dlgSignUp_lblHelpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dlgSignUpLayout.createSequentialGroup()
                                    .addComponent(dlgSignUp_tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dlgSignUp_lblUserOk)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dlgSignUp_cbbDefaultUser))
                            .addContainerGap(25, Short.MAX_VALUE))
                        .addGroup(dlgSignUpLayout.createSequentialGroup()
                            .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(dlgSignUpLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dlgSignUp_lblHelpPassword)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dlgSignUp_tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(dlgSignUpLayout.createSequentialGroup()
                                    .addComponent(dlgSignUp_tfPassConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dlgSignUp_lblPassOk)
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        dlgSignUpLayout.setVerticalGroup(
            dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgSignUpLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dlgSignUp_tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgSignUp_lblHelpUserName)
                    .addComponent(jLabel8)
                    .addComponent(dlgSignUp_lblUserOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlgSignUp_cbbDefaultUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dlgSignUp_tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgSignUp_lblHelpPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgSignUp_tfPassConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(dlgSignUp_lblPassOk)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(dlgSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgSignUp_rbtCancel)
                    .addComponent(dlgSignUp_btSignUp))
                .addContainerGap())
        );

        javax.swing.GroupLayout dlgPortfoliosLayout = new javax.swing.GroupLayout(dlgPortfolios.getContentPane());
        dlgPortfolios.getContentPane().setLayout(dlgPortfoliosLayout);
        dlgPortfoliosLayout.setHorizontalGroup(
            dlgPortfoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgPortfoliosLayout.setVerticalGroup(
            dlgPortfoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dlgMoving.setTitle("Trade move");
        dlgMoving.setResizable(false);

        jLabel6.setText("Current trade");

        dlgMoving_lblCurrentTrade.setText("...");

        jLabel11.setText("Move to portfilio");

        dlgMoving_cbbChoosePortfolio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose portfilio", "Item 2", "Item 3", "Item 4" }));

        dlgMoving_btMove.setText("Move");

        dlgMoving_btCancel.setText("Cancel");

        javax.swing.GroupLayout dlgMovingLayout = new javax.swing.GroupLayout(dlgMoving.getContentPane());
        dlgMoving.getContentPane().setLayout(dlgMovingLayout);
        dlgMovingLayout.setHorizontalGroup(
            dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgMovingLayout.createSequentialGroup()
                .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgMovingLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgMovingLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(dlgMoving_lblCurrentTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgMovingLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dlgMoving_cbbChoosePortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dlgMovingLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(dlgMoving_btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(dlgMoving_btMove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgMovingLayout.setVerticalGroup(
            dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgMovingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dlgMoving_lblCurrentTrade))
                .addGap(28, 28, 28)
                .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dlgMoving_cbbChoosePortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(dlgMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgMoving_btMove)
                    .addComponent(dlgMoving_btCancel))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        dlgManage_btnAdd.setText("Add");

        dlgManage_btnEdit.setText("Edit");

        dlgManage_btnDelete.setText("Delete");

        jButton1.setText("Cancel");

        jScrollPane2.setViewportView(jList1);

        jLabel13.setText("Portfolio id: ");

        jLabel14.setText("Portfolio name:");

        jLabel15.setText("Portfolio type:");

        dlgManage_lblId.setText("...");

        jLabel17.setText("Available cash:");

        dlgManage_cbbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real", "Test" }));

        dlgManage_cbByDefault.setText("Use by default");

        javax.swing.GroupLayout dlgManageLayout = new javax.swing.GroupLayout(dlgManage.getContentPane());
        dlgManage.getContentPane().setLayout(dlgManageLayout);
        dlgManageLayout.setHorizontalGroup(
            dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgManageLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgManageLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(21, 21, 21)
                                .addComponent(dlgManage_lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgManageLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(5, 5, 5)
                                .addComponent(dlgManage_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(dlgManageLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(5, 5, 5)
                                    .addComponent(dlgManage_cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dlgManageLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dlgManage_cbByDefault)
                                        .addComponent(dlgManage_tfCash))))))
                    .addGroup(dlgManageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dlgManage_btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dlgManage_btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dlgManage_btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgManageLayout.setVerticalGroup(
            dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgManageLayout.createSequentialGroup()
                        .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(dlgManage_lblId))
                        .addGap(18, 18, 18)
                        .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(dlgManage_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(dlgManage_cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(dlgManage_tfCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dlgManage_cbByDefault)))
                .addGap(18, 18, 18)
                .addGroup(dlgManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(dlgManage_btnAdd)
                    .addComponent(dlgManage_btnEdit)
                    .addComponent(dlgManage_btnDelete))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        dlgManageLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dlgManage_btnAdd, dlgManage_btnDelete, dlgManage_btnEdit, jButton1});

        ppMain_Move.setText("Move trade");
        ppMain.add(ppMain_Move);
        ppMain.add(jSeparator2);

        ppMain_Delete.setText("Delete trade");
        ppMain.add(ppMain_Delete);

        dlgAdd.setResizable(false);

        jLabel16.setText("Number of Shares");

        javax.swing.GroupLayout dlgAddLayout = new javax.swing.GroupLayout(dlgAdd.getContentPane());
        dlgAdd.getContentPane().setLayout(dlgAddLayout);
        dlgAddLayout.setHorizontalGroup(
            dlgAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        dlgAddLayout.setVerticalGroup(
            dlgAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel16)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblStatus.setText("Status");
        getContentPane().add(lblStatus, java.awt.BorderLayout.PAGE_END);

        tTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Symbol", "Quantity", "Entry", "Last", "Change", "Value", "Gain/Loss", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tTable);
        tTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblTotal.setText("sdfsdfsdfsd");

        btAddTrade.setText("Add Trade/Trade Now");

        btDeleteTrade.setText("Delete Trade");

        btSaveChanges.setText("Save Changes");

        cbbPortfolio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choosen Portfolio", "Item 2", "Item 3", "Item 4" }));

        cbIsDefaultPortfolio.setText("use by default");

        btMove.setText("Move to another portfolio");
        btMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoveActionPerformed(evt);
            }
        });

        btRefresh.setText("Refresh");

        jLabel9.setText("Portfolio:");

        jLabel2.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(317, 317, 317))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbbPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbIsDefaultPortfolio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAddTrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDeleteTrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbbPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIsDefaultPortfolio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAddTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btDeleteTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btMove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        mFile.setText(" File ");

        smExpExcel.setText("Export to Excel");
        mFile.add(smExpExcel);

        smExpCsv.setText("Export to CSV");
        mFile.add(smExpCsv);
        mFile.add(jSeparator1);

        smExit.setText("Exit");
        mFile.add(smExit);

        jMenuBar1.add(mFile);

        mTrade.setText(" Add trade/Trade now ");
        jMenuBar1.add(mTrade);

        mSwitch.setText(" Switch to Test Mode ");
        jMenuBar1.add(mSwitch);

        mPortfolios.setText(" Manage portfolios ");
        jMenuBar1.add(mPortfolios);

        mReports.setText(" Create report ");

        smReportCurrent.setText("Current portfolio");
        mReports.add(smReportCurrent);

        smReportAll.setText("All portfolios");
        mReports.add(smReportAll);

        jMenuBar1.add(mReports);

        mEmpty.setText("                                                                                                          ");
        jMenuBar1.add(mEmpty);

        mUser.setText("User:                               ");
        jMenuBar1.add(mUser);

        mLogin.setText("Log In/Out");
        mLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mLoginMouseClicked(evt);
            }
        });
        jMenuBar1.add(mLogin);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dlgUser_btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgUser_btCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgUser_btCancelActionPerformed

    private void dlgSignUp_rbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgSignUp_rbtCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgSignUp_rbtCancelActionPerformed

    private void dlgSignUp_tfPassConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgSignUp_tfPassConfirmationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgSignUp_tfPassConfirmationActionPerformed

    private void mLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLoginMouseClicked
        dlgUser_lblPasswordOk.pack();
        dlgUser_lblPasswordOk.setLocationRelativeTo(null);
        dlgUser_lblPasswordOk.setVisible(true);
    }//GEN-LAST:event_mLoginMouseClicked

    private void btMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTrade;
    private javax.swing.JButton btDeleteTrade;
    private javax.swing.JButton btMove;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSaveChanges;
    private javax.swing.JCheckBox cbIsDefaultPortfolio;
    private javax.swing.JComboBox<String> cbbPortfolio;
    private javax.swing.JDialog dlgAdd;
    private javax.swing.JDialog dlgManage;
    private javax.swing.JButton dlgManage_btnAdd;
    private javax.swing.JButton dlgManage_btnDelete;
    private javax.swing.JButton dlgManage_btnEdit;
    private javax.swing.JCheckBox dlgManage_cbByDefault;
    private javax.swing.JComboBox<String> dlgManage_cbbType;
    private javax.swing.JLabel dlgManage_lblId;
    private javax.swing.JTextField dlgManage_tfCash;
    private javax.swing.JTextField dlgManage_tfName;
    private javax.swing.JDialog dlgMoving;
    private javax.swing.JButton dlgMoving_btCancel;
    private javax.swing.JButton dlgMoving_btMove;
    private javax.swing.JComboBox<String> dlgMoving_cbbChoosePortfolio;
    private javax.swing.JLabel dlgMoving_lblCurrentTrade;
    private javax.swing.JDialog dlgPortfolios;
    private javax.swing.JDialog dlgSignUp;
    private javax.swing.JButton dlgSignUp_btSignUp;
    private javax.swing.JCheckBox dlgSignUp_cbbDefaultUser;
    private javax.swing.JLabel dlgSignUp_lblHelpPassword;
    private javax.swing.JLabel dlgSignUp_lblHelpUserName;
    private javax.swing.JLabel dlgSignUp_lblPassOk;
    private javax.swing.JLabel dlgSignUp_lblUserOk;
    private javax.swing.JButton dlgSignUp_rbtCancel;
    private javax.swing.JPasswordField dlgSignUp_tfPassConfirmation;
    private javax.swing.JPasswordField dlgSignUp_tfPassword;
    private javax.swing.JTextField dlgSignUp_tfUsername;
    private javax.swing.JButton dlgUser_btCancel;
    private javax.swing.JButton dlgUser_btLogin;
    private javax.swing.JButton dlgUser_btSignUp;
    private javax.swing.JCheckBox dlgUser_cbbDefaultUser;
    private javax.swing.JLabel dlgUser_lblHelpPassword;
    private javax.swing.JLabel dlgUser_lblHelpUserName;
    private javax.swing.JDialog dlgUser_lblPasswordOk;
    private javax.swing.JLabel dlgUser_lblUserOk;
    private javax.swing.JPasswordField dlgUser_tfPassword;
    private javax.swing.JTextField dlgUser_tfUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenu mEmpty;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mLogin;
    private javax.swing.JMenu mPortfolios;
    private javax.swing.JMenu mReports;
    private javax.swing.JMenu mSwitch;
    private javax.swing.JMenu mTrade;
    private javax.swing.JMenu mUser;
    private javax.swing.JPopupMenu ppMain;
    private javax.swing.JMenuItem ppMain_Delete;
    private javax.swing.JMenuItem ppMain_Move;
    private javax.swing.JMenuItem smExit;
    private javax.swing.JMenuItem smExpCsv;
    private javax.swing.JMenuItem smExpExcel;
    private javax.swing.JMenuItem smReportAll;
    private javax.swing.JMenuItem smReportCurrent;
    private javax.swing.JTable tTable;
    // End of variables declaration//GEN-END:variables
}
